Sistema/ViewModels/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Sistema.ViewModels
{
    public class UsuarioViewModel
    {
        //public Usuario usuario { get; set; }
        public int id { get; set; }

        public string email { get; set; }

        [Required]
        [DisplayName("Nome de Login")]
        public string login { get; set; }

        [DisplayName("Nome")]
        public String Nome { get; set; }

        [DisplayName("Último Login")]
        public DateTime ultimoLogin { get; set; }

        [DisplayName("Data de Criação")]
        public DateTime dataCriacao { get; set; }

        [DisplayName("Está Online?")]
        public bool estaOnline { get; set; }

        [DisplayName("Está Bloqueado?")]
        public bool estaBloqueado { get; set; }

        public IList<System.Web.Mvc.SelectListItem> papeisList { get; set; }

        public int IdProfessor { get; set; }

        [DisplayName("Professor")]
        public IList<System.Web.Mvc.SelectListItem> professorList { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "A {0} deve ser de {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Senha { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirma Senha")]
        [Compare("Senha", ErrorMessage = "As senhas digitadas não coincidem.")]
        public string ConfirmaSenha { get; set; }

    }
}

Sistema/Controllers/UsuariosController.cs
using Infrastructure.Domain.Base.GenericRepository;
using Infrastructure.Domain.Models;
using Infrastructure.Domain.Models.Escola;
using Infrastructure.Domain.Repositories;
using Infrastructure.Service.Security;
using Infrastructure.Service.Tools.Drawing;
using Sistema.Helpers.DataTable;
using Sistema.Helpers.Attributes;
using Sistema.Helpers.DataTable;
using Sistema.ViewModels;
using Sistema.ViewModels.Mappers;
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Sistema.Controllers
{
    [AuthorizeRoles("Administrador")]
    public class UsuariosController : FeatureController
    {
        private IPapelRepositorio papelRepositorio;
        private IGenericRepository genericRepositorio;
        public const string IMAGES_DIR = "~/Content/Images/Usuarios/";

        private DataTable<Usuario> dataTable = new DataTable<Usuario>();
        
        public UsuariosController(IGenericRepository generic_Repositorio,
            IPapelRepositorio papel_Repositorio)
        {
            this.genericRepositorio = generic_Repositorio;
            this.papelRepositorio = papel_Repositorio;

            dataTable
                .addColumn(x => x.id)
                .addColumn(x => x.login, "Login")
                .addColumn(x => x.ultimoLogin).setCssClass("align-center");
        }

        [HttpPost]
        public DataTableResult DataTableIndex(DataTablePostData dataTablePostData)
        {
            return dataTable.getDataTableResultEF(ControllerContext, genericRepositorio.Tudo<Usuario>().AsQueryable(), dataTablePostData);
        }

        //
        // GET: /Usuarios/
        public ActionResult Index()
        {
            return View(dataTable.renderDataTable());
        }

        //
        // GET: /Usuarios/Details/5
        public ActionResult Details(int id)
        {
            return View(genericRepositorio.EncontrarPorID<Usuario>(id));
        }

        //
        // GET: /Usuarios/Create
        public ActionResult Create()
        {
            UsuariosViewModelMapper mapper = new UsuariosViewModelMapper(genericRepositorio);
            return View(mapper.exportaViewModel(new Usuario(genericRepositorio)));
        }

        //
        // POST: /Usuarios/Create
        [HttpPost]
        public ActionResult Create(UsuarioViewModel item, int[] ids)
        {
            try
            {
                if (ids == null)
                {
                    string erro = "Por favor, informe pelo menos um nível de acesso.";
                    informaErro(erro);
                    ModelState.AddModelError("", erro);
                }

                var professor = genericRepositorio.EncontrarPor<Professor>(x => x.id == item.IdProfessor).FirstOrDefault();
                item.login = professor.Login;
                item.Nome = professor.Nome;
                item.email = professor.email;

                var existelogin = genericRepositorio.EncontrarPor<Usuario>(x => x.login == item.login).FirstOrDefault();

                if (item.Senha == item.ConfirmaSenha && existelogin == null) //ModelState.IsValid && 
                {
                    genericRepositorio.UnitOfWork.BeginTransaction();
                    UsuariosViewModelMapper mapper = new UsuariosViewModelMapper(genericRepositorio);
                    Usuario usuario = mapper.importaViewModel(item);

                    usuario.Senha = Criptography.HashCode(item.Senha);

                    usuario.papeis = genericRepositorio.EncontrarPor<Papel>(x => ids.Contains(x.id)).ToList();
                    usuario.dataCriacao = DateTime.Now;
                    usuario.ultimoLogin = new DateTime(1900, 1, 1);

                    usuario.professor = professor;

                    genericRepositorio.Adicionar<Usuario>(usuario);
                    genericRepositorio.UnitOfWork.CommitTransaction();

                    informaSucesso("Registro salvo com sucesso!");
                    return RedirectToAction("Index");
                }
                else
                {
                    item.papeisList = genericRepositorio.Tudo<Papel>().Select(c => new SelectListItem() { Text = c.nome, Value = c.id.ToString() }).ToList();
                    item.professorList = genericRepositorio.Tudo<Professor>().Select(c => new SelectListItem() { Text = c.Nome, Value = c.id.ToString() }).ToList();
                    informaErro("Faltam informações ou o professor já é usuário do sistema.");
                    return View(item);
                }
            }
            catch (Exception e)
            {
                informaErro(e.Message);
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Usuarios/Edit/5
        public ActionResult Edit(int id, int[] ids)
        {
            try
            {
                UsuariosViewModelMapper mapper = new UsuariosViewModelMapper(genericRepositorio);

                Usuario u = genericRepositorio.EncontrarPor<Usuario>(p=>p.papeis).Where(p=>p.id == id).FirstOrDefault();
                return View(mapper.exportaViewModel(u));
            }
            catch (Exception e)
            {
                informaErro(e.Message);
                return RedirectToAction("Index");
            }
        }

        //
        // POST: /Usuarios/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, UsuarioViewModel item, int[] ids)
        {
            try
            {
                if (ModelState.IsValid && item.Senha == item.ConfirmaSenha)
                {
                    UsuariosViewModelMapper mapper = new UsuariosViewModelMapper(genericRepositorio);
                    Usuario usuario = mapper.importaViewModel(item);

                    if (ids != null)
                    {

                        genericRepositorio.UnitOfWork.BeginTransaction();

                        //recupera os papeis do usuario, apaga eles, adiciona os novos
                        //tenho que fazer isto pq o usuario que vem da view vem com lista de papeis "desconectada"
                        Usuario usr = genericRepositorio.EncontrarPor<Usuario>(p => p.papeis).Where(p => p.id == usuario.id).FirstOrDefault();
                        usuario.papeis = usr.papeis;
                        var papeisnovos = genericRepositorio.EncontrarPor<Papel>(x => ids.Contains(x.id)).ToList();
                        usuario.papeis.Clear();
                        foreach (var reg in papeisnovos)
                        {
                            usuario.papeis.Add(reg);
                        }

                        usuario.Senha = Criptography.HashCode(item.Senha);

                        var professor = genericRepositorio.EncontrarPor<Professor>(x => x.id == item.IdProfessor).FirstOrDefault();
                        usuario.professor = professor;

                        genericRepositorio.Atualizar<Usuario>(usuario);
                        genericRepositorio.UnitOfWork.CommitTransaction();

                    }
                    else
                        genericRepositorio.Atualizar<Usuario>(usuario);

                    informaSucesso("Registro salvo com sucesso!");
                    return RedirectToAction("Index");
                }
                else
                {
                    item.papeisList = genericRepositorio.Tudo<Papel>().Select(c => new SelectListItem() { Text = c.nome, Value = c.id.ToString() }).ToList();
                    item.professorList = genericRepositorio.Tudo<Professor>().Select(c => new SelectListItem() { Text = c.Nome, Value = c.id.ToString() }).ToList();
                    return View(item);
                }
            }
            catch (Exception e)
            {
                informaErro(e.Message);
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Usuarios/Delete/5
        public ActionResult Delete(int id)
        {
            return View(genericRepositorio.EncontrarPor<Usuario>(p => p.professor, p=>p.papeis).Where(p => p.id == id).FirstOrDefault());
            
        }

        //
        // POST: /Usuarios/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, Usuario u)
        {
            try
            {
                genericRepositorio.UnitOfWork.BeginTransaction();
                genericRepositorio.Deletar<Usuario>(genericRepositorio.EncontrarPorID<Usuario>(id));
                genericRepositorio.UnitOfWork.CommitTransaction();
                informaSucesso("Registro apagado com sucesso!");
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                informaErro(e.Message);
                return RedirectToAction("Index");
            }
        }

        [AllowAnonymous]
        public FileResult Foto(string login)
        {
            string filename = IMAGES_DIR + "000000.jpg";

            if (login != null)
            {
                //Usuario usuario = genericRepositorio.EncontrarPor<Usuario>(x => x.login.ToLower() == login.ToLower()).IncludeMultiple(p=>p.professor).FirstOrDefault();
                Usuario usuario = genericRepositorio.Tudo<Usuario>(p => p.professor).Where(x => x.login.ToLower() == login.ToLower()).FirstOrDefault();

                if (usuario != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(IMAGES_DIR + usuario.professor.Nome + ".jpg")))
                    {
                        filename = IMAGES_DIR + usuario.professor.Nome + ".jpg";
                    }
                    else if (System.IO.File.Exists(Server.MapPath(IMAGES_DIR + usuario.login + ".jpg")))
                    {
                        filename = IMAGES_DIR + usuario.login + ".jpg";
                    }
                    else
                    {

Sistema/Views/Usuarios/Create.cshtml
@model UsuarioViewModel

<div class="page-header" >
    <h2>Novo Usuário</h2>
</div>

@using (Html.BeginForm())
{
    @Html.Partial("_CamposFormulario")
    <div class="well">
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> Criar</button>
        @Html.LinkVoltarAListagem()
    </div>
}

@section scripts{
    <script type="text/javascript">
        $(function () {

            $('#IdProfessor').click(function () {
                var widget = {
                    pIdProfessor: $('#IdProfessor').val()
                };

                $.ajax({
                    url: "/Usuarios/Buscar",
                    async: true,
                    type: "post",
                    datatype: 'json',
                    data: JSON.stringify(widget),
                    contentType: 'application/json',
                    success: function (data) {
                        $('#dados').empty();
                        $('#dados').append(data);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert(textStatus + " / " + errorThrown);
                    }
                });

            });
        });
    </script>
}

Sistema/Views/Usuarios/Delete.cshtml
@model Usuario

<div class="page-title">
    <h1>USUÁRIOS</h1>
</div>

@using (Html.BeginForm())
{
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h4>EXCLUIR USUÁRIO?</h4>
        </div>
        <div class="panel-body">
            @Html.Partial("_CamposDetalhe")
        </div>
        <div class="panel-footer text-right">
            @Html.LinkVoltarAListagem()
            <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Excluir</button>
        </div>
    </div>
}

Sistema/Views/Usuarios/Details.cshtml
@model Usuario

<div class="page-title">
    <h1>USUÁRIOS</h1>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>DETALHES DO USUÁRIO</h4>
    </div>
    <div class="panel-body">
        @Html.Partial("_CamposDetalhe")
    </div>
    <div class="panel-footer text-right">
        @Html.LinkVoltarAListagem()
        @if (User.IsInRole("Desenvolvedor"))
        {
            @Html.LinkEditar(Model.id)
        }
    </div>
</div>

Sistema/Views/Usuarios/Edit.cshtml
@model UsuarioViewModel

<div class="page-title">
    <h1>USUÁRIOS</h1>
</div>

@using (Html.BeginForm())
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>EDITAR USUÁRIO</h4>
        </div>
        <div class="panel-body">
            @Html.Partial("_CamposFormulario")
        </div>
        <div class="panel-footer text-right">
            @Html.LinkVoltarAListagem()
            <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> Alterar</button>
        </div>
    </div>
}

Sistema/Views/Usuarios/Index.cshtml
@model DataTableViewData<Usuario>

<div class="page-title">
    <h1>USUÁRIOS</h1>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>LISTA DE USUÁRIOS</h4>
    </div>
    <div class="panel-body">
        @Html.DrawDataTable(Model)
    </div>
    <div class="panel-footer text-right">
        @Html.LinkCriarNovo()
    </div>
</div>

@section scripts {
    @Html.DrawDataTableHeader(ViewContext, Model)
}

Sistema/Views/Usuarios/_CamposDetalhe.cshtml
@model Usuario

<div class="row">
    <div class="col-md-2">
        <img src="@Url.Content("/Content/Images/loading.gif")" class="profile-img img-circle" data-src="@Url.Action("Foto", "Usuarios", new { login = Model.login })" />
    </div>
    <div class="col-md-10">
        <h2 class="text-primary" style="margin-top: 0;">
            @Model.professor.Nome 
            @if (Model.estaOnline == true)
            {
                <img src="@Url.Content("/Content/Images/Icons/bullet-green.png")" data-toggle="tooltip" data-original-title="Usuário Online" />
            }
            else
            {
                <img src="@Url.Content("/Content/Images/Icons/bullet-grey.png")" data-toggle="tooltip" data-original-title="Usuário Offline" />
            }
        </h2>
        <ul class="list-unstyled">
            <li><label><i class="glyphicon glyphicon-envelope"></i> E-mail:</label> @Model.professor.email</li>
            <li><label> Telefone:</label> @Model.professor.Telefone</li>
            <li><label> E-mail:</label> @Model.professor.email</li>
            <li><label> Endereço:</label> @Model.professor.Endereco</li>
        </ul>
        <p class="text-muted">Usuário criado dia @String.Format("{0:g}", Model.dataCriacao), o último login foi feito dia @String.Format("{0:g}", Model.ultimoLogin).</p>
    </div>
</div>

Sistema/Views/Usuarios/_CamposFormulario.cshtml
@model UsuarioViewModel

<div class="form-group">
    <div class="row">
        <div class="col-md-2">
            <img id="foto" src="@Url.Content("/Content/Images/loading.gif")" class="profile-img img-circle" data-src="@Url.Action("Foto", "Usuarios", new { login = Model.login })" />
        </div>
        <div class="col-md-10">
            <div class="row">
                <div class="col-md-8">
                    @Html.LabelFor(model => model.professorList)
                    @Html.DropDownListFor(model => model.IdProfessor, Model.professorList, String.Empty, new { @class = "form-control", data_behaviour = "select2", data_placeholder = "Escolha uma opção" })
                </div>
            </div>
            <div class="row" >
                <div class="col-md-4" >
                    <div id="dados" ></div>
                    @*@Html.LabelFor(model => model.login)
                    @Html.TextBoxFor(model => model.login, new { @class = "form-control", @readonly = true })
                    @Html.ValidationMessageFor(model => model.login)*@
                </div>

            </div>
            @*<div class="row">
                <div class="col-md-4">
	                @Html.LabelFor(model => model.email)
                    @Html.TextBoxFor(model => model.email, new { @class = "form-control", @readonly = true })
                    @Html.ValidationMessageFor(model => model.email)
                </div>
            </div>*@

            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Senha)
                    @Html.TextBoxFor(model => model.Senha, new { @class = "form-control", type = "password" })
                    @Html.ValidationMessageFor(model => model.Senha)
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.ConfirmaSenha)
                    @Html.TextBoxFor(model => model.ConfirmaSenha, new { @class = "form-control", type = "password" })
                    @Html.ValidationMessageFor(model => model.ConfirmaSenha)
                </div>
            </div>

        </div>
    </div>
</div>
	
<div class="form-group">
	@Html.LabelFor(model => model.papeisList)
	@Html.EditorFor(model => model.papeisList, "CheckBoxList", new { name = "ids" })
	@Html.ValidationMessageFor(model => model.papeisList)
</div>

@Html.HiddenFor(model => model.id)
@Html.ValidationMessageFor(model => model.id)
	
@Html.HiddenFor(model => model.dataCriacao)
@Html.HiddenFor(model => model.ultimoLogin)