Sistema/ViewModels/LoginViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Sistema.ViewModels
{
    public class LoginViewModel
    {
        public string returnUrl { get; set; }

        [Required]
        [DisplayName("Login")]
        public virtual string login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [DisplayName("Senha")]
        public virtual string senha { get; set; }
    }

    public class RegisterExternalLoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public string ExternalLoginData { get; set; }
    }

    public class LocalPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ExternalLogin
    {
        public string Provider { get; set; }
        public string ProviderDisplayName { get; set; }
        public string ProviderUserId { get; set; }
    }
}

Sistema/Controllers/ContaController.cs
using Infrastructure.Domain.Models;
using Infrastructure.Domain.Repositories;
using Newtonsoft.Json;
using Sistema.Helpers;
using Sistema.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Linq;
using Infrastructure.Domain;
using Infrastructure.Domain.Base.GenericRepository;
using WebMatrix.WebData;
using Microsoft.Web.WebPages.OAuth;
using Infrastructure.Service.Security;

namespace Sistema.Controllers
{
    public class ContaController : FeatureController
    {
        private IUsuarioRepositorio usuarioRepositorio;
        private IGenericRepository genericRepositorio;

        public ContaController(IUsuarioRepositorio usuario_repositorio, IGenericRepository generic_repositorio)
        {
            this.usuarioRepositorio = usuario_repositorio;
            this.genericRepositorio = generic_repositorio;
        }

        //
        // GET: /Conta/Login
        public ActionResult Login(string ReturnUrl)
        {
            ViewData.Clear(); // Não renderiza a mesma mensagem exibida duas vezes
            return View(new LoginViewModel() { returnUrl = ReturnUrl });
        }

        //
        // GET: /Conta/Trocar
        public ActionResult Trocar()
        {
            //remover cookie
            HttpCookie cookie;

            cookie = Request.Cookies["sistema-login"];
            cookie.Expires = DateTime.Now.AddDays(-1);
            Response.SetCookie(cookie);

            cookie = Request.Cookies["sistema-nome"];
            cookie.Expires = DateTime.Now.AddDays(-1);
            Response.SetCookie(cookie);

            cookie = Request.Cookies["sistema-email"];
            cookie.Expires = DateTime.Now.AddDays(-1);
            Response.SetCookie(cookie);

            return RedirectToAction("Login");
        }

        //
        // GET: /Conta/Login
        [HttpPost]
        public ActionResult Login(string ReturnUrl, LoginViewModel item)
        {
            Usuario usuario;

            try
            {
                //Valida dados de login e senha 
                if (ModelState.IsValid) //  && WebSecurity.Login(item.login, item.senha, persistCookie: true)
                {
                    string username = item.login.ToLower();
                    string password = item.senha;

                    if (usuarioRepositorio.validateUser(username, password))
                    {

                        //criação do cookie
                        HttpCookie cookie;

                        var perfil = genericRepositorio.EncontrarPor<Usuario>(p=>p.professor).Where(p => p.login == username).FirstOrDefault();

                        cookie = new HttpCookie("sistema-login");
                        cookie.Value = item.login;
                        cookie.Expires = DateTime.Now.AddMonths(1);
                        Response.SetCookie(cookie);

                        cookie = new HttpCookie("sistema-nome");
                        cookie.Value = perfil.professor.Nome;
                        cookie.Expires = DateTime.Now.AddMonths(1);
                        Response.SetCookie(cookie);

                        cookie = new HttpCookie("sistema-email");
                        cookie.Value = perfil.professor.email;
                        cookie.Expires = DateTime.Now.AddMonths(1);
                        Response.SetCookie(cookie);

                        // preenchemos a sessão com os dados para ser renderizados no menu
                        usuario = genericRepositorio.FindOne<Usuario>(x => x.login == item.login);
                        Session.Add("usuario", usuario);
                        Session.Add("usuarioId", usuario.id);

                        // Grant cookie and redirect (to admin home if not otherwise specified)
                        FormsAuthentication.SetAuthCookie(item.login, false);

                        genericRepositorio.UnitOfWork.BeginTransaction();
                        usuario.ultimoLogin = DateTime.Now;
                        usuario.estaOnline = true;
                        genericRepositorio.Atualizar<Usuario>(usuario);
                        genericRepositorio.UnitOfWork.CommitTransaction();

                        SetupFormsAuthTicket(usuario, true);

                        //se foi autorizado mais a senha é padrão
                        //redirect mudança de senha
                        if (password == "123456")
                            return RedirectToAction("Manage");

                        // E redirecionamos para o local desejado
                        return Redirect(String.IsNullOrWhiteSpace(ReturnUrl) ? Url.Action("Index", "Home") : ReturnUrl);
                    }
                    else
                    {
                        informaErro("Senha incorreta");
                    }
                }
                else
                {
                    informaErro("Digite os campos obrigatórios e tente novamente.");
                }

                return View(item);
            }
            catch (Exception e)
            {
                informaErro(e.Message);
                return View(item);
            }
        }

        //
        // GET: /Conta/Logoff
        public ActionResult Logoff()
        {
            if (Session["usuario"] != null)
            {
                genericRepositorio.UnitOfWork.BeginTransaction();
                Usuario usuario = Session["usuario"] as Usuario;
                usuario.estaOnline = false;
                genericRepositorio.Atualizar<Usuario>(usuario);
                genericRepositorio.UnitOfWork.CommitTransaction();
            }

            FormsAuthentication.SignOut();
            Session.RemoveAll();

            informaAviso("Sua sessão foi encerrada!");

            return RedirectToAction("Login");
        }

        private bool SetupFormsAuthTicket(Usuario user, bool persistanceFlag)
        {
            var userData = user.id.ToString();
            var authTicket = new FormsAuthenticationTicket(1, //version
                                                        user.login, // login
                                                        DateTime.Now,             //creation
                                                        DateTime.Now.AddMinutes(30), //Expiration
                                                        persistanceFlag, //Persistent
                                                        userData);

            var encTicket = FormsAuthentication.Encrypt(authTicket);
            Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName, encTicket));
            return true;
        }

        //
        // GET: /Account/Manage

        public ActionResult Manage(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Sua senha foi alterada com sucesso."
                : message == ManageMessageId.SetPasswordSuccess ? "Sua senha foi definida."
                : message == ManageMessageId.RemoveLoginSuccess ? "Login externo foi removido."
                : "";

            Usuario usr = (Usuario)Session["usuario"];

            ViewBag.Nome = usr.professor.Nome;

            //ViewBag.HasLocalPassword = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
            ViewBag.ReturnUrl = Url.Action("Manage");
            return View();
        }

        //
        // POST: /Account/Manage

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage(LocalPasswordModel model)
        {
            //bool hasLocalAccount = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
            //ViewBag.HasLocalPassword = hasLocalAccount;
            ViewBag.ReturnUrl = Url.Action("Manage");
            //if (hasLocalAccount)
            //{
                if (ModelState.IsValid)
                {
                    // ChangePassword will throw an exception rather than return false in certain failure scenarios.
                    Usuario usuario = genericRepositorio.EncontrarPor<Usuario>().Where(p => p.login == User.Identity.Name).FirstOrDefault();
                    genericRepositorio.UnitOfWork.BeginTransaction();
                    usuario.Senha = Criptography.HashCode(model.NewPassword);  //usuarioRepositorio.CriptografiaMD5(model.NewPassword);
                    genericRepositorio.Atualizar<Usuario>(usuario);
                    genericRepositorio.UnitOfWork.CommitTransaction();

                    //WebSecurity.CreateAccount(User.Identity.Name, model.NewPassword);

                    //bool changePasswordSucceeded;
                    //try
                    //{
                    //    changePasswordSucceeded = WebSecurity.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword);
                    //}
                    //catch (Exception)
                    //{
                    //    changePasswordSucceeded = false;
                    //}

                    //if (changePasswordSucceeded)
                    //{
                        return RedirectToAction("Index", "Home", new { Message = ManageMessageId.ChangePasswordSuccess });
                    //}
                    //else
                    //{
                    //    ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
                    //}
                }
            //}
            //else
            //{
                // User does not have a local password so remove any validation errors caused by a missing
                // OldPassword field
                //ModelState state = ModelState["OldPassword"];
                //if (state != null)
                //{
                //    state.Errors.Clear();
                //}

                //if (ModelState.IsValid)
                //{

Sistema/Views/Conta/ExternalLoginConfirmation.cshtml
@model MvcApplication1.Models.RegisterExternalLoginModel
@{
    ViewBag.Title = "Register";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>Associate your @ViewBag.ProviderDisplayName account.</h2>
</hgroup>

@using (Html.BeginForm("ExternalLoginConfirmation", "Account", new { ReturnUrl = ViewBag.ReturnUrl })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Association Form</legend>
        <p>
            You've successfully authenticated with <strong>@ViewBag.ProviderDisplayName</strong>.
            Please enter a user name for this site below and click the Confirm button to finish
            logging in.
        </p>
        <ol>
            <li class="name">
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
            </li>
        </ol>
        @Html.HiddenFor(m => m.ExternalLoginData)
        <input type="submit" value="Register" />
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sistema/Views/Conta/ExternalLoginFailure.cshtml
@{
    ViewBag.Title = "Login Failure";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>Unsuccessful login with service.</h2>
</hgroup>

Sistema/Views/Conta/Login.cshtml
@model LoginViewModel
@{
    Layout = "~/Views/Shared/_Login.cshtml";
    ViewBag.Title = "Autenticação requerida";

    var loginInCookie = Request.Cookies["sistema-login"];
}

<div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
    @*<img src="@Url.Content("/Content/Images/fermat.jpg")" style="width: 250px;" />*@
    <h1 class="text-center login-title">Login no Sistema</h1>
    <div class="account-wall">

        @if (loginInCookie != null)
        {
            <img class="profile-img img-circle" src="@Url.Content("/Content/Images/loading.gif")" data-src="@Url.Action("Foto", "Usuarios", new { login = loginInCookie.Value })" alt="Usuário">
        }
        else
        {
            <img class="profile-img img-circle" src="@Url.Action("Foto", "Usuarios")" alt="Usuário">
        }

        @using (Html.BeginForm())
        {
            if (loginInCookie != null)
            {
                <p class="profile-name">@Request.Cookies["sistema-nome"].Value</p>
                <span class="profile-email">@Request.Cookies["sistema-email"].Value</span>
                @Html.Hidden("login", loginInCookie.Value)

                @Html.TextBoxFor(model => model.senha, new { @class = "form-control only-password", type = "password", autofocus = true, placeholder = "Senha" })
            }
            else
            {
                @Html.TextBoxFor(model => model.login, new { @class = "form-control", autofocus = true, placeholder = "Login" })
                @Html.TextBoxFor(model => model.senha, new { @class = "form-control", type = "password", placeholder = "Senha" })
            }

            <button class="btn btn-lg btn-primary btn-block" data-loading-text="Aguarde..." type="submit">Fazer login</button>
        }

        <!-- NOTIFICATIONS -->
        @if (ViewData["error"] != null)
        {
            <div class="alert alert-danger alert-dismissable">
                <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                <strong>Erro: </strong>@ViewData["error"]
            </div>
        }
        @if (ViewData["warning"] != null)
        {
            <div class="alert alert-warning alert-dismissable">
                <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                <strong>Atenção: </strong>@ViewData["warning"]
            </div>
        }
        @if (ViewData["success"] != null)
        {
            <div class="alert alert-success alert-dismissable">
                <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                <strong>Sucesso: </strong>@ViewData["success"]
            </div>
        }
        @if (ViewData["info"] != null)
        {
            <div class="alert alert-info alert-dismissable">
                <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                <strong>Informação: </strong>@ViewData["success"]
            </div>
        }
    </div>
    @if (loginInCookie != null)
    {
        @Html.ActionLink("Acesse com uma conta diferente", "Trocar", null, new { @class = "text-center switch-account" })
    }
</div>

Sistema/Views/Conta/Manage.cshtml
@model Sistema.ViewModels.LocalPasswordModel
@{
    ViewBag.Title = "Alteração de Senha";
}

<div class="page-header">
    <h2>@ViewBag.Title.</h2>
</div>

<div class="form-horizontal">
    <p class="message-success">@ViewBag.StatusMessage</p>

    <p>You're logged in as <strong>@ViewBag.Nome</strong>.</p>

    @Html.Partial("_ChangePasswordPartial")

</div>

    @*@if (ViewBag.HasLocalPassword)
        {

        }
        else
        {*@
    @*@Html.Partial("_SetPasswordPartial")*@
    @*}*@

    @*<section id="externalLogins">
            @Html.Action("RemoveExternalLogins")

            <h3>Add an external login</h3>
            @Html.Action("ExternalLoginsList", new { ReturnUrl = ViewBag.ReturnUrl })
        </section>*@

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Sistema/Views/Conta/_ChangePasswordPartial.cshtml
@model Sistema.ViewModels.LocalPasswordModel

<h3>Insira a nova senha</h3>

@using (Html.BeginForm("Manage", "Conta"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="form-group">
        <div class="row">
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.OldPassword)
                        @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.NewPassword)
                        @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.ConfirmPassword)
                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 well">
        <div class="bottom-area">
            <input type="submit" value="Alterar Senha" class="btn btn-success" />
        </div>
    </div>
}

Sistema/Views/Conta/_ExternalLoginsListPartial.cshtml
@model ICollection<Microsoft.Web.WebPages.OAuth.AuthenticationClientData>

@if (Model.Count == 0)
{
    <div class="message-info">
        <p>
            There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=252166">this article</a>
            for details on setting up this ASP.NET application to support logging in via external services.
        </p>
    </div>
}
else
{
    using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = ViewBag.ReturnUrl }))
    {
        @Html.AntiForgeryToken()
        <fieldset id="socialLoginList">
            <legend>Log in using another service</legend>
            <p>
                @foreach (Microsoft.Web.WebPages.OAuth.AuthenticationClientData p in Model)
                {
                    <button type="submit" name="provider" value="@p.AuthenticationClient.ProviderName" title="Log in using your @p.DisplayName account">@p.DisplayName</button>
                }
            </p>
        </fieldset>
    }
}

Sistema/Views/Conta/_RemoveExternalLoginsPartial.cshtml
@model ICollection<MvcApplication1.Models.ExternalLogin>

@if (Model.Count > 0)
{
    <h3>Registered external logins</h3>
    <table>
        <tbody>
        @foreach (MvcApplication1.Models.ExternalLogin externalLogin in Model)
        {
            <tr>
                <td>@externalLogin.ProviderDisplayName</td>
                <td>
                    @if (ViewBag.ShowRemoveButton)
                    {
                        using (Html.BeginForm("Disassociate", "Account"))
                        {
                            @Html.AntiForgeryToken()
                            <div>
                                @Html.Hidden("provider", externalLogin.Provider)
                                @Html.Hidden("providerUserId", externalLogin.ProviderUserId)
                                <input type="submit" value="Remove" title="Remove this @externalLogin.ProviderDisplayName credential from your account" />
                            </div>
                        }
                    }
                    else
                    {
                        @: &nbsp;
                    }
                </td>
            </tr>
        }
        </tbody>
    </table>
}